# Generated by Django 3.0.6 on 2020-05-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser", name="is_superuser", field=models.BooleanField(),
        ),
    ]
