# Generated by Django 3.0.7 on 2020-07-23 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0002_auto_20200724_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='file',
            new_name='filelocation',
        ),
    ]
