# Generated by Django 3.0.3 on 2020-03-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0003_auto_20200310_1502'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
