# Generated by Django 2.2.4 on 2020-03-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0003_auto_20200313_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
