# Generated by Django 3.0.1 on 2020-03-12 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0004_auto_20200311_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2020, 3, 12, 18, 55, 27, 293451)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 3, 12, 18, 55, 27, 293427)),
        ),
    ]
