# Generated by Django 2.2.4 on 2020-03-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0004_auto_20200313_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(default='MBBS', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(default='Brain', max_length=50),
        ),
    ]
