# Generated by Django 3.0.6 on 2020-05-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0004_auto_20200508_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='type',
            new_name='typeof',
        ),
    ]
