# Generated by Django 3.0.6 on 2020-06-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0006_auto_20200603_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='type',
            new_name='type_of',
        ),
    ]
