# Generated by Django 3.0.6 on 2020-06-05 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0008_auto_20200603_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndivdualDoctorQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.Doctor')),
            ],
        ),
    ]
