# Generated by Django 3.0.6 on 2020-06-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0009_indivdualdoctorqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='indivdualdoctorqueue',
            name='queue',
            field=models.ManyToManyField(to='clinic_app.Appointment'),
        ),
    ]
