# Generated by Django 3.0.3 on 2020-06-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0010_indivdualdoctorqueue_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='daily_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='daily_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
