# Generated by Django 2.2.4 on 2020-03-13 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0015_auto_20200313_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(choices=[('MBBS', 'MBBS'), ('BDS', 'BDS'), ('BHMS', 'BHMS'), ('DHMS', 'DHMS'), ('BAMS', 'BAMS'), ('BUMS', 'BUMS'), ('BVSc & AH', 'BVSc & AH'), ('B.Pharm.', 'B.Pharm.'), ('D.Pharm.', 'D.Pharm.'), ('BOT', 'BOT'), ('BMLT', 'BMLT'), ('BPT', 'BPT'), ('B.Sc. Nursing', 'B.Sc. Nursing'), ('BNYS', 'BNYS')], default='MBBS', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2020, 3, 13, 13, 28, 58, 1477), null=True),
        ),
    ]
